version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-17hp8yvy4mg6d"
s3_prefix = "sam-app"
region = "ap-northeast-1"
profile = "terraform"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
