AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  template-app
  This template is updated from Hello-World Application which is SAM sample application.

Parameters:
  Environment: 
    Description: An environment type. Development, Validation, Staging, Commercial.
    Type: String
    AllowedValues: [dev, val, stg, prod]
    Default: dev 

  ProjectCode:
    Description: Project code of system. (ttNNN)
    Type: String
    Default: tt005

Mappings:
  # AWS Region ------------------------------------------
  AWSRegionToRGN:
    ap-northeast-1:
      RGN: apne1
    us-east-1:
      RGN: uset1

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 25 # Less than API Gateawy maximum timeout (29 sec).
    Runtime: python3.8
    Handler: app.lambda_handler
    VpcConfig: 
      SubnetIds: 
        Fn::Split:
          - ","
          - Fn::ImportValue: !Sub
              - ApplicationSubnetIDs-${Environment}-${Region}-${ProjectCode}
              - Environment: !Ref Environment
                Region: !FindInMap [AWSRegionToRGN, !Ref "AWS::Region", RGN]
                ProjectCode: !Ref ProjectCode
      SecurityGroupIds: 
        Fn::Split:
          - ","
          - Fn::ImportValue: !Sub
              - ApplicationSGIDs-${Environment}-${Region}-${ProjectCode}
              - Environment: !Ref Environment
                Region: !FindInMap [AWSRegionToRGN, !Ref "AWS::Region", RGN]
                ProjectCode: !Ref ProjectCode

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
